version: '3.8'

services:
  db:
    image: postgres:17.0
    environment:
      POSTGRES_DB: 'taskdb'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:6.0.20
    ports:
      - '6379:6379'
    networks:
      - backend

  web:
    build: .
    command: gunicorn taskmanager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend

  celery:
    build: .
    command: celery -A taskmanager worker -l info
    volumes:
      - .:/app
      - media_volume:/app/media
    depends_on:
      - web
      - redis
    env_file:
      - .env
    networks:
      - backend
    
  celery-beat:
    build: .
    command: celery -A taskmanager beat -l info
    volumes:
      - .:/app
      - media_volume:/app/media
    depends_on:
      - web
      - redis
    env_file:
      - .env
    networks:
      - backend

volumes:
  db_data:
  media_volume:

networks:
  backend: 
    driver: bridge